<?php
/**
 * implements hook_block_info()
 */
 function manatus_calendar_block_info(){
 	$blocks['custom-range-calendar'] = array(
 	 'info' => t('Custom range calendar'),
 	 'cache' => DRUPAL_NO_CACHE,
 	);
  /*$blocks['custom-range-calendar2'] = array(
   'info' => t('Custom range calendar no. 2'),
   'cache' => DRUPAL_NO_CACHE,
  );*/
 	return $blocks;
 }

 /**
 * Implements hook_block_view().
 */
function manatus_calendar_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    /*case 'custom-range-calendar':
	  	$block['content'] = array(
		    '#markup' => _manatus_calendar_show_calendar(),
		    '#attached' => array(
		        'js' => array(
		    	      drupal_get_path('module', 'manatus_calendar') . '/js/jquery.min.js',  // v.2.1.3
		    	      drupal_get_path('module', 'manatus_calendar') . '/js/bootstrap.min.js', // v.3.3.2
		    	      drupal_get_path('module', 'manatus_calendar') . '/js/moment.min.js',
		    	      drupal_get_path('module', 'manatus_calendar') . '/js/daterangepicker.js',
		    	      drupal_get_path('module', 'manatus_calendar') . '/js/global.js', //custom js for the calendar
			      ),
		        'css' => array(
		    	      drupal_get_path('module', 'manatus_calendar') . '/css/bootstrap.min.css', // v.3.3.2
		    	      drupal_get_path('module', 'manatus_calendar') . '/css/daterangepicker.css', 
		    	      drupal_get_path('module', 'manatus_calendar') . '/css/global.css', //custom css for the calendar
			      ),
			    ),
			  );
      break;*/
      case 'custom-range-calendar':
      $block['content'] = array(
        '#markup' => _manatus_calendar_show_calendar(),
        '#attached' => array(
            'js' => array(
                //drupal_get_path('module', 'manatus_calendar') . '/datepicker/js/jquery.js',  // 
                drupal_get_path('module', 'manatus_calendar') . '/datepicker/js/datepicker.js', // 
                drupal_get_path('module', 'manatus_calendar') . '/datepicker/js/eye.js',
                drupal_get_path('module', 'manatus_calendar') . '/datepicker/js/utils.js',
                drupal_get_path('module', 'manatus_calendar') . '/datepicker/js/layout.js', //
            ),
            'css' => array(
                drupal_get_path('module', 'manatus_calendar') . '/datepicker/css/datepicker.css', // 
                drupal_get_path('module', 'manatus_calendar') . '/datepicker/css/layout.css', 
            ),
          ),
        );
      break;
  }
  return $block;
}

/**
 * Custom function 'show calendar'
 */
 /*function _manatus_calendar_show_calendar(){
  
  $options = "";
  for ($i=0; $i < 10; $i++) { 
    $options .= "<option value=\"".$i."\">".$i."</option>";
  }
  
  $people = $options;
  $rooms = $options;

  $people = "<option value=\"np\" selected=\"selected\">".t('Number of people')."</option>".$people;
  $rooms = "<option value=\"nr\" selected=\"selected\">".t('Number of rooms')."</option>".$rooms;

 	return '<form class="reservation-form" enctype="multipart/form-data" action="/" method="get" accept-charset="UTF-8">
            <div class="row">
              <div class="col-md-12 col-md-offset-0 demo">
                <h2>'.t('Make your reservation').'</h4>
                <div class="wrapper">
                  <input type="text" id="checkin-checkout" class="form-control" name="checkin-checkout">
                </div>
                <div class="wrapper-select np">
                  <select id="edit-submitted-selects-number-of-people" name="submitted[selects][number_of_people]" class="form-select">
                   '.$people.'
                  </select>
                </div>
                <div class="wrapper-select">
                  <select id="edit-submitted-selects-number-of-rooms" name="submitted[selects][number_of_rooms]" class="form-select">
                   '.$rooms.'
                  </select>
                </div>
                <div class="wrapper-submit">
                  <input type="submit" id="edit-submit" name="op" value="BOOK NOW" class="form-submit">
                </div>
              </div>
            </div>
          </form>';
 }*/

 /**
 * Custom function 'show calendar #2'
 */
 function _manatus_calendar_show_calendar(){
  
  $options = "";
  global $language;
  for ($i=1; $i <= 10; $i++) { 
    $options .= "<option value=\"".$i."\">".$i."</option>";
  }
  
  $people = $options;
  $rooms = $options;

  $people = "<option value=\"0\" selected=\"selected\">".t('Number of people')."</option>".$people;
  $rooms = "<option value=\"0\" selected=\"selected\">".t('Number of rooms')."</option>".$rooms;
  $selection = 'Apply selection';
  if($language->language == 'es'){
    $selection = 'Aplicar selección';
  }

  return '<form class="reservation-form" enctype="multipart/form-data" data-lang="' . $language->language . '" action="http://booking.manatuscostarica.com/reservacion_'. $language->language .'_paso1.aspx" method="get" accept-charset="UTF-8">
            <div class="row">
              <div class="col-md-12 col-md-offset-0 demo">
                <h2>'.t('Make your reservation').'</h4>
                
                  <div id="widget">
                    <div id="widgetField">
                      <input type="text" id="checkin-checkout" class="form-control hidden" name="rango_fecha" value="">
                      <div id="checkin-checkout-selector" class="form-control">'.t('Select range').'</div>
                    </div>
                    <div id="widgetCalendar" class="hidden"><div id="loader-calendar"></div><a id="aplicar-seleccion" href="javascript:void(0)">' . $selection . '</a>
                    </div>
                  </div>

                <div class="wrapper-select np">
                  <select id="edit-submitted-selects-number-of-people" name="people" class="form-select">
                   '.$people.'
                  </select>
                </div>
                <div class="wrapper-select">
                  <select id="edit-submitted-selects-number-of-rooms" name="rooms" class="form-select">
                   '.$rooms.'
                  </select>
                </div>
                <div class="wrapper-submit">
                  <input type="submit" id="edit-submit" name="op" value="' . t('BOOK NOW') . '" class="form-submit lang">
                </div>
              </div>
            </div>
          </form>';
 }

 /**
  * hook_menu() //prueba
  */
function manatus_calendar_menu(){
 $items['json-dates/%/%/%'] = array(
    'access callback' => TRUE,
    'page callback' => '_manatus_calendar_get_json_dates',
    'page arguments' => array(1,2,3),
    'delivery callback' => 'drupal_json_output'
  );
  return $items;
}

/*custom function*/
function _manatus_calendar_get_json_dates($month, $year, $lang){

  //consultar 
  $postData = array('month' => $month, 'year' => $year, 'lang' => $lang);
  $fechas = consultarURL("http://booking.manatuscostarica.com/FechasNoDisponibles.asmx/GetDates", $postData);
  $JsonObject = json_decode((String)$fechas);
  /*var_dump($JsonObject->fechas);
  exit();
  return array(
    '20-10-2015',
    '21-10-2015',
    '22-10-2015',
    '23-10-2015',
    );*/
  return $JsonObject->fechas;
}

function consultarURL($url, $postData = array()){
  $header = array('Content-Type: application/x-www-form-urlencoded');
  // set up the request
  $curl = curl_init($url);
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);  // have curl_exec return a string
  //curl_setopt($curl, CURLOPT_HTTPHEADER, array('Accept: application/json', 'X-CSRF-Token: ' .$csrf_token)); // Accept JSON response
  curl_setopt($curl, CURLOPT_HTTPHEADER, $header); // Accept JSON response
  curl_setopt($curl, CURLOPT_POST, 1); // Do a regular HTTP POST
  curl_setopt($curl, CURLOPT_HEADER, FALSE);  // Ask to not return Header
  curl_setopt($curl, CURLOPT_POSTFIELDS, "month=" . $postData['month'] . "&year=" . $postData['year'] . "&lang=" . $postData['lang']); // POST this data
  curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, FALSE);
  curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, FALSE);
  // make the request
  curl_setopt($curl, CURLOPT_VERBOSE, true); // output to command line
  $response = curl_exec($curl);
  curl_close($curl);
  $xml = new SimpleXMLElement($response);
  return $xml;
}